### ISSUE TITLE
Harbor Terraform Module

### ISSUE THREAD

**Issue by TheRubick** [Hassan-Eid-Hassan/terraform-devops-tools#3]
Hello Hassan,
Would you mind if I have added to this repo a module for **harbor registry**?

**Comment by Hassan-Eid-Hassan** [comment]
Hello Muhammad,

For sure, contributions are welcome! Please follow these steps to contribute:

Fork the repository.

Create a new branch with your changes.

Submit a pull request explaining your changes.

 Thanks,
Hassan Eid.
